import Vue from 'vue';
import { Form, Field, Button, Toast, Swipe, SwipeItem, Grid, GridItem, NavBar, GoodsAction, GoodsActionIcon, GoodsActionButton, SubmitBar, Checkbox, Card, Tag, Stepper, AddressList, AddressEdit, Area, ContactCard, SwipeCell, Popup, Tab, Tabs, List, Cell, Icon,Search,Divider } from 'vant'; 

Vue.use(Divider);
Vue.use(Search);
Vue.use(Icon);
Vue.use(Cell);
Vue.use(List);
Vue.use(Tab);
Vue.use(Tabs);
Vue.use(Popup);
Vue.use(SwipeCell);
Vue.use(ContactCard);
Vue.use(Area);
Vue.use(AddressEdit);
Vue.use(AddressList);
Vue.use(Stepper);
Vue.use(Tag);
Vue.use(Card);
Vue.use(Checkbox);
Vue.use(SubmitBar);
Vue.use(GoodsAction);
Vue.use(GoodsActionButton);
Vue.use(GoodsActionIcon);
Vue.use(NavBar);
Vue.use(Grid);
Vue.use(GridItem);
Vue.use(Swipe);
Vue.use(SwipeItem);
Vue.use(Button);
Vue.use(Form);
Vue.use(Field);
Vue.use(Toast);